# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constrs/nexys_a7.xdc

# IP: ip/BRAM/BRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM || ORIG_REF_NAME==BRAM} -quiet] -quiet
