# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/2-lab2/2-lab1/2-lab1.cache/wt [current_project]
set_property parent.project_path E:/2-lab2/2-lab1/2-lab1.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/2-lab2/2-lab1/2-lab1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/second/sys3lab-2022-stu-master/src/lab2/lab2.coe
add_files d:/computer_system/sys3/sys3lab-2022-stu/src/lab2/lab2.coe
read_verilog E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/imports/src/AluOp.vh
read_verilog -library xil_defaultlib -sv {
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/imports/src/IO_Manager.sv
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/imports/src/Top.sv
}
read_verilog -library xil_defaultlib {
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/Bextend.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/CSR.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/Cache.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/imports/src/Control.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/imports/src/Core.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/imports/new/EX_MEM.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/Extend.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/ForwardingControl.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/ID_EX.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/IF.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/IF_ID.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/I_Cache.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/Iextend.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/Jextend.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/imports/lab2/LatencyMemory.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/MEM_WB.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/Regs.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/imports/src/SCPU.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/Sextend.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/Uextend.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/alu1.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/iLatencyMemory.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/mem_valid_sig.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/mux2.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/mux3.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/stallControl.v
  E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/new/trans_addrCSR.v
}
read_ip -quiet E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/ip/BRAM/BRAM.xci
set_property used_in_implementation false [get_files -all e:/2-lab2/2-lab1/2-lab1.srcs/sources_1/ip/BRAM/BRAM_ooc.xdc]

read_ip -quiet E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/ip/BRAM2/BRAM2.xci
set_property used_in_implementation false [get_files -all e:/2-lab2/2-lab1/2-lab1.srcs/sources_1/ip/BRAM2/BRAM2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/2-lab2/2-lab1/2-lab1.srcs/constrs_1/imports/constrs/nexys_a7.xdc
set_property used_in_implementation false [get_files E:/2-lab2/2-lab1/2-lab1.srcs/constrs_1/imports/constrs/nexys_a7.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Top -part xc7a100tcsg324-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
