# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/1vivado/2-lab1/2-lab1.srcs/sources_1/ip/rom1/rom1.xci
# IP: The module: 'rom1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/1vivado/2-lab1/2-lab1.srcs/sources_1/ip/rom1/rom1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/1vivado/2-lab1/2-lab1.srcs/sources_1/ip/rom1/rom1.xci
# IP: The module: 'rom1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/1vivado/2-lab1/2-lab1.srcs/sources_1/ip/rom1/rom1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
