# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/ip/BRAM2/BRAM2.xci
# IP: The module: 'BRAM2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/2-lab2/2-lab1/2-lab1.srcs/sources_1/ip/BRAM2/BRAM2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/2-lab2/2-lab1/2-lab1.srcs/sources_1/ip/BRAM2/BRAM2.xci
# IP: The module: 'BRAM2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/2-lab2/2-lab1/2-lab1.srcs/sources_1/ip/BRAM2/BRAM2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
